//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningRobot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleaningRobot.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result file path cannot be empty string.
        /// </summary>
        internal static string EmptyResultFilePath {
            get {
                return ResourceManager.GetString("EmptyResultFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result file path &apos;{0}&apos; indicates directory instead of file.
        /// </summary>
        internal static string InvalidResultFilePath {
            get {
                return ResourceManager.GetString("InvalidResultFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid starting point &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidStartingPoint {
            get {
                return ResourceManager.GetString("InvalidStartingPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of battery.
        /// </summary>
        internal static string OutOfBattery {
            get {
                return ResourceManager.GetString("OutOfBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back off strategy failed, robot stuck.
        /// </summary>
        internal static string RobotStuck {
            get {
                return ResourceManager.GetString("RobotStuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file path &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string SourceFileNotFound {
            get {
                return ResourceManager.GetString("SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide two input parameters as &lt;source.json&gt; &lt;result.json&gt;.
        /// </summary>
        internal static string TwoParametersRequired {
            get {
                return ResourceManager.GetString("TwoParametersRequired", resourceCulture);
            }
        }
    }
}
